// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {theme} from '../models';
import {render} from '../models';

export function GetRecentFiles():Promise<Array<string>>;

export function GetStartupFile():Promise<string>;

export function GetStartupTheme():Promise<string>;

export function ListThemes():Promise<Array<theme.Info>>;

export function LoadRemoteImage(arg1:string):Promise<string>;

export function OpenFile(arg1:string):Promise<render.DocumentPayload>;

export function PickFile():Promise<string>;

export function ResolveTheme(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
