// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function GetStartupTheme() {
  return window['go']['main']['App']['GetStartupTheme']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function ResolveTheme(arg1) {
  return window['go']['main']['App']['ResolveTheme'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
